import type { Metadata } from "next";
import "./globals.scss";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import GarazeTheme from "@/components/AntDesignTheme";
import { ReactNode } from "react";
import SessionWrapper from "@/components/Auth/SessionWrapper";
import AuthWrapper from "@/components/Auth/AuthWrapper";
import { SelectedSpotProvider } from "./context/SelectedSpotProvider";

import QueryProvider from "@/components/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <SessionWrapper>

          <AuthWrapper>
            <SelectedSpotProvider>
            <AntdRegistry>
              <QueryProvider>
                <GarazeTheme>{children}</GarazeTheme>
              </QueryProvider>
            </AntdRegistry>
            </SelectedSpotProvider>
          </AuthWrapper>
        </SessionWrapper>
      </body>
    </html>
  );
}
