import type { Metadata } from "next";
import "./globals.scss";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import GarazeTheme from "@/components/AntDesignTheme";
import { ReactNode } from "react";
import "@ant-design/v5-patch-for-react-19";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <AntdRegistry>
          <GarazeTheme>{children}</GarazeTheme>
        </AntdRegistry>
      </body>
    </html>
  );
}
