import type { Metadata } from "next";
import "./globals.scss";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import GarazeTheme from "@/components/AntDesignTheme";
import { ReactNode } from "react";
import "@ant-design/v5-patch-for-react-19";
import SessionWrapper from "@/components/Auth/SessionWrapper";
import QueryClientWrapper from "./context/QueryClientProvider";
import { SelectedSpotProvider } from "./context/SelectedSpotProvider";

// import AuthWrapper from "@/components/Auth/AuthWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <SessionWrapper>
          <QueryClientWrapper>
            {/* <Navbar /> */}
          {/* <AuthWrapper> */}
            <SelectedSpotProvider>
            <AntdRegistry>
              <GarazeTheme>{children}</GarazeTheme>
            </AntdRegistry>
            </SelectedSpotProvider>
          {/* </AuthWrapper> */}
          </QueryClientWrapper>
        </SessionWrapper>
      </body>
    </html>
  );
}
